# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: music.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'music.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmusic.proto\x12\x05music\"\x07\n\x05\x45mpty\"1\n\x05Music\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06\x61rtist\x18\x03 \x01(\t\")\n\tMusicList\x12\x1c\n\x06musics\x18\x01 \x03(\x0b\x32\x0c.music.Music\"\x17\n\tMusicById\x12\n\n\x02id\x18\x01 \x01(\x05\"2\n\x12\x43reateMusicRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x61rtist\x18\x02 \x01(\t\"\\\n\x12UpdateMusicRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\x04name\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x13\n\x06\x61rtist\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\x07\n\x05_nameB\t\n\x07_artist\"2\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xfd\x01\n\x0cMusicService\x12)\n\x07\x46indAll\x12\x0c.music.Empty\x1a\x10.music.MusicList\x12)\n\x07\x46indOne\x12\x10.music.MusicById\x1a\x0c.music.Music\x12\x31\n\x06\x43reate\x12\x19.music.CreateMusicRequest\x1a\x0c.music.Music\x12\x31\n\x06Update\x12\x19.music.UpdateMusicRequest\x1a\x0c.music.Music\x12\x31\n\x06\x44\x65lete\x12\x10.music.MusicById\x1a\x15.music.DeleteResponseB\x1eZ\x1cmusic-manager-go/proto/musicb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'music_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\034music-manager-go/proto/music'
  _globals['_EMPTY']._serialized_start=22
  _globals['_EMPTY']._serialized_end=29
  _globals['_MUSIC']._serialized_start=31
  _globals['_MUSIC']._serialized_end=80
  _globals['_MUSICLIST']._serialized_start=82
  _globals['_MUSICLIST']._serialized_end=123
  _globals['_MUSICBYID']._serialized_start=125
  _globals['_MUSICBYID']._serialized_end=148
  _globals['_CREATEMUSICREQUEST']._serialized_start=150
  _globals['_CREATEMUSICREQUEST']._serialized_end=200
  _globals['_UPDATEMUSICREQUEST']._serialized_start=202
  _globals['_UPDATEMUSICREQUEST']._serialized_end=294
  _globals['_DELETERESPONSE']._serialized_start=296
  _globals['_DELETERESPONSE']._serialized_end=346
  _globals['_MUSICSERVICE']._serialized_start=349
  _globals['_MUSICSERVICE']._serialized_end=602
# @@protoc_insertion_point(module_scope)
