# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import playlist_pb2 as playlist__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in playlist_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PlaylistServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FindAll = channel.unary_unary(
                '/playlist.PlaylistService/FindAll',
                request_serializer=playlist__pb2.Empty.SerializeToString,
                response_deserializer=playlist__pb2.PlaylistList.FromString,
                _registered_method=True)
        self.FindOne = channel.unary_unary(
                '/playlist.PlaylistService/FindOne',
                request_serializer=playlist__pb2.PlaylistById.SerializeToString,
                response_deserializer=playlist__pb2.Playlist.FromString,
                _registered_method=True)
        self.FindMusics = channel.unary_unary(
                '/playlist.PlaylistService/FindMusics',
                request_serializer=playlist__pb2.PlaylistById.SerializeToString,
                response_deserializer=playlist__pb2.MusicList.FromString,
                _registered_method=True)
        self.FindUsers = channel.unary_unary(
                '/playlist.PlaylistService/FindUsers',
                request_serializer=playlist__pb2.PlaylistById.SerializeToString,
                response_deserializer=playlist__pb2.UserList.FromString,
                _registered_method=True)
        self.Create = channel.unary_unary(
                '/playlist.PlaylistService/Create',
                request_serializer=playlist__pb2.CreatePlaylistRequest.SerializeToString,
                response_deserializer=playlist__pb2.Playlist.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/playlist.PlaylistService/Update',
                request_serializer=playlist__pb2.UpdatePlaylistRequest.SerializeToString,
                response_deserializer=playlist__pb2.Playlist.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/playlist.PlaylistService/Delete',
                request_serializer=playlist__pb2.PlaylistById.SerializeToString,
                response_deserializer=playlist__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.AddMusic = channel.unary_unary(
                '/playlist.PlaylistService/AddMusic',
                request_serializer=playlist__pb2.AddMusicToPlaylistRequest.SerializeToString,
                response_deserializer=playlist__pb2.AddMusicResponse.FromString,
                _registered_method=True)
        self.RemoveMusic = channel.unary_unary(
                '/playlist.PlaylistService/RemoveMusic',
                request_serializer=playlist__pb2.RemoveMusicFromPlaylistRequest.SerializeToString,
                response_deserializer=playlist__pb2.DeleteResponse.FromString,
                _registered_method=True)


class PlaylistServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FindAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindOne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindMusics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddMusic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveMusic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlaylistServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FindAll': grpc.unary_unary_rpc_method_handler(
                    servicer.FindAll,
                    request_deserializer=playlist__pb2.Empty.FromString,
                    response_serializer=playlist__pb2.PlaylistList.SerializeToString,
            ),
            'FindOne': grpc.unary_unary_rpc_method_handler(
                    servicer.FindOne,
                    request_deserializer=playlist__pb2.PlaylistById.FromString,
                    response_serializer=playlist__pb2.Playlist.SerializeToString,
            ),
            'FindMusics': grpc.unary_unary_rpc_method_handler(
                    servicer.FindMusics,
                    request_deserializer=playlist__pb2.PlaylistById.FromString,
                    response_serializer=playlist__pb2.MusicList.SerializeToString,
            ),
            'FindUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.FindUsers,
                    request_deserializer=playlist__pb2.PlaylistById.FromString,
                    response_serializer=playlist__pb2.UserList.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=playlist__pb2.CreatePlaylistRequest.FromString,
                    response_serializer=playlist__pb2.Playlist.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=playlist__pb2.UpdatePlaylistRequest.FromString,
                    response_serializer=playlist__pb2.Playlist.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=playlist__pb2.PlaylistById.FromString,
                    response_serializer=playlist__pb2.DeleteResponse.SerializeToString,
            ),
            'AddMusic': grpc.unary_unary_rpc_method_handler(
                    servicer.AddMusic,
                    request_deserializer=playlist__pb2.AddMusicToPlaylistRequest.FromString,
                    response_serializer=playlist__pb2.AddMusicResponse.SerializeToString,
            ),
            'RemoveMusic': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveMusic,
                    request_deserializer=playlist__pb2.RemoveMusicFromPlaylistRequest.FromString,
                    response_serializer=playlist__pb2.DeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'playlist.PlaylistService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('playlist.PlaylistService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlaylistService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FindAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/playlist.PlaylistService/FindAll',
            playlist__pb2.Empty.SerializeToString,
            playlist__pb2.PlaylistList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/playlist.PlaylistService/FindOne',
            playlist__pb2.PlaylistById.SerializeToString,
            playlist__pb2.Playlist.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindMusics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/playlist.PlaylistService/FindMusics',
            playlist__pb2.PlaylistById.SerializeToString,
            playlist__pb2.MusicList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/playlist.PlaylistService/FindUsers',
            playlist__pb2.PlaylistById.SerializeToString,
            playlist__pb2.UserList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/playlist.PlaylistService/Create',
            playlist__pb2.CreatePlaylistRequest.SerializeToString,
            playlist__pb2.Playlist.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/playlist.PlaylistService/Update',
            playlist__pb2.UpdatePlaylistRequest.SerializeToString,
            playlist__pb2.Playlist.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/playlist.PlaylistService/Delete',
            playlist__pb2.PlaylistById.SerializeToString,
            playlist__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddMusic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/playlist.PlaylistService/AddMusic',
            playlist__pb2.AddMusicToPlaylistRequest.SerializeToString,
            playlist__pb2.AddMusicResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveMusic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/playlist.PlaylistService/RemoveMusic',
            playlist__pb2.RemoveMusicFromPlaylistRequest.SerializeToString,
            playlist__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
